//https://learning.edx.org/course/course-v1:HarvardX+AT1x+2T2024/block-v1:HarvardX+AT1x+2T2024+type@sequential+block@2778af6879ee4c6c9c7710578bc52fc8/block-v1:HarvardX+AT1x+2T2024+type@vertical+block@924ac947048e4c33a1d48ff5adddd9d8?_gl=1%2Axfvhr7%2A_gcl_au%2AMTY2MTkzNDc4OC4xNzIwMzE5NjY4%2A_ga%2AMTEwOTQyNDIzNy4xNzIwMzE5NjY4%2A_ga_D3KS4KMDT0%2AMTcyMDU2ODg3NS4yLjEuMTcyMDU2ODk0OC40OC4wLjA.

export const basicAnatomicalTerms = {
  "standard anatomical position": "face forward, palms of the hands forward, feet flat on the floor",
  "supine": "lying face upwards",
  "prone": "lying face downward",
  "aspect": "view: how you're looking at the patient",
  "anterior aspect": "view from the front",
  "posterior aspect": "view from the back",
  "lateral aspect": "view from the side",
  "superficial": "closer to the body surface",
  "deep": "farther away from the body surface",
  "superior": "closer to the head",
  "inferior": "closer to the feet",
  "medial": "closer to midline",
  "lateral": "farther from the midline",
  "proximal": "closer to the heart",
  "distal": "farther away from the heart",
  "head": "head",
  "neck": "neck",
  "thorax": "chest",
  "abdomen": "between the thorax and the pelvis",
  "pelvis": "lower part of the abdomen",
  "upper limb": "commonly known as arm",
  "brachium": "upper arm fancy",
  "arm": "upper arm simple",
  "antebrachium": "forearm",
  "hand": "hand",
  "lower limb": "hip to feet",
  "crus": "knee to ankle fancy",
  "leg": "knee to ankle simple",
  "foot": "foot",
  "thigh": "thigh",
  "sagittal plane": "divides body into left and right",
  "coronal plane": "divides body into anterior and posterior sections",
  "orthogonal": "at a right angle",
  "axial plane": "divides body into transverse sections",
  "central regions of the body": "head, neck, thorax, abdomen & pelvis"
}