import {  TermObject } from "./deckObject";


export const anatomicalTerms: TermObject = {
  "anatomy" : "the study of the structure of the body",
  "physiology" : "the study of the function of the body",
  "developmental" : "studies structure changes from fertilization to death",
  "gross" : "structures that can be examined without using a microscope",
  "regional" : "specific regions of the body such as head or chest",
  "systemic" : "structure of specific body systems such as nervous or respiratory",
  "surface" : "external features",
  "microscopic" : "structures that need a microscope to view",
  "chemical" : "level of organization: atoms and molecules",
  "cellular" : "level of organization: molecules that combine",
  "tissue" : "level of organization: groups of cells that work together to perform a specific function",
  "organ" : "level of organization: structures composed of at least two types of tissues",
  "system" : "level of organization: related organs with a common function",
  "organism" : "level of organization: a whole living individual",
  "integumentary" : "body system: skin & structures associated with it",
  "skeletal" : "body system: bones & joints",
  "muscular" : "body system: brings about body movements",
  "nervous" : "body system: brain, spinal cord & nerves",
  "endocrine" : "body system: hormone-producing glands & cells",
  "cardiovascular" : "body system: blood, heart & vessels",
  "lymphatic" : "body system: fluid, vessels & cells associated with immune response",
  "respiratory" : "body system: lungs & air passageways",
  "digestive" : "body system: physical & chemical breakdown of food",
  "urinary" : "body system: eliminates waste & regulates chemical composition of blood",
  "reproductive" : "body system: gonads & associated organs",
  "coronal" : "vertical body plane that divides body into front and back ('crown')",
  "frontal" : "vertical body plane that divides body into front and back ('not crown')",
  "transverse" : "horizontal body plane that divides body into top and bottom",
  "median" : "vertical body plane that divides body into equal left and right sides ('half')",
  "sagittal" : "vertical body plane that divides body into equal left and right sides ('arrow')",
  "paramedian" : "vertical body plane that divides body into unequal left and right sides ('half')",
  "parasagittal" : "vertical body plane that divides body into unequal left and right sides ('arrow')",
  "oblique" : "body plane that passes through on an angle",
  "superior" : "towards the head ('better')",
  "inferior" : "away from head ('not as good')",
  "cranial" : "towards the head (fancy)",
  "caudal" : "away from head (towards tail)",
  "anterior" : "towards front of body",
  "posterior" : "towards back of body",
  "proximal" : "towards the origin",
  "distal" : "away from origin",
  "medial" : "closer to midline",
  "lateral" : "farther from midline",
  "flexion" : "motion that decreases joint angle",
  "extension" : "motion that increases joint angle",
  "adduction" : "move towards midline of body",
  "abduction" : "move away from midline of body",
  "lateral flexion" : "moving away from midline of body; bending sideways",
  "radial deviation" : "wrist tilt towards thumb",
  "ulnar deviation" : "wrist tilt towards pinky finger",
  "rotation" : "turning about the axis of the body",
  "medial rotation" : "internal rotation (incl. 'rotation')",
  "lateral rotation" : "external rotation (incl. 'rotation')",
  "supination" : "palms up",
  "pronation" : "palms down",
  "inversion" : "foot flexed and sickled inward (sole of foot faces midline)",
  "eversion" : "foot flexed and sickled outward (sole of foot faces away from midline)",
  "axial skeleton" : "axis around which the body moves",
  "appendicular skeleton" : "the appendages",
  "anatomical position" : "standing, facing forward, palms of hands facing forward",
  "dorsiflexion" : "flexing the foot upward",
  "plantarflexion" : "pointing the food downward"
}