//https://learning.edx.org/course/course-v1:HarvardX+AT1x+2T2024/block-v1:HarvardX+AT1x+2T2024+type@sequential+block@2778af6879ee4c6c9c7710578bc52fc8/block-v1:HarvardX+AT1x+2T2024+type@vertical+block@924ac947048e4c33a1d48ff5adddd9d8?_gl=1%2Axfvhr7%2A_gcl_au%2AMTY2MTkzNDc4OC4xNzIwMzE5NjY4%2A_ga%2AMTEwOTQyNDIzNy4xNzIwMzE5NjY4%2A_ga_D3KS4KMDT0%2AMTcyMDU2ODg3NS4yLjEuMTcyMDU2ODk0OC40OC4wLjA.

export const basicAnatomicalTerms = {
  "standard anatomical position": "face forward, palms of the hands forward, feet flat on the floor",
  "supine": "lying face upwards",
  "prone": "lying face downward",
  "aspect": "view: how you're looking at the patient",
  "anterior aspect": "view from the front",
  "posterior aspect": "view from the back",
  "lateral aspect": "view from the side",
  "superficial": "closer to the body surface",
  "deep": "farther away from the body surface",
  "superior": "closer to the head",
  "inferior": "closer to the feet",
  "medial": "closer to midline",
  "lateral": "farther from the midline",
  "proximal": "closer to the heart",
  "distal": "farther away from the heart",
  "head": "head",
  "neck": "neck",
  "thorax": "chest",
  "abdomen": "between the thorax and the pelvis",
  "pelvis": "lower part of the abdomen",
  "upper limb": "commonly known as arm",
  "brachium": "upper arm fancy",
  "arm": "upper arm simple",
  "antebrachium": "forearm",
  "hand": "hand",
  "lower limb": "hip to feet",
  "crus": "knee to ankle fancy",
  "leg": "knee to ankle simple",
  "foot": "foot",
  "thigh": "thigh",
  "sagittal plane": "divides body into left and right",
  "coronal plane": "divides body into anterior and posterior sections",
  "orthogonal": "at a right angle",
  "axial plane": "divides body into transverse sections",
  "central regions of the body": "head, neck, thorax, abdomen & pelvis"
}

export const cellParts = {
  "hierarchy of organization": "cells, tissues, organs, organ systems, organisms",
  "cell": "smallest independent unit of living tissue",
  "plasma membrane": "provides selective barrier between extracellular and intracellular environment",
  "cytoplasm": "cytoskeleton and cytosol",
  "cytoskeleton": "network of tubules and filaments inside cell",
  "cytosol": "cell gel",
  "boundary membrane": "surrounds organelles",
  "organelles": "functional components of cells",
  "nucleus": "largest of cell organelles",
  "nuclear envelope": "nuclear membrane",
  "deoxyribonucleic acid": "DNA",
  "nucleolus": "site of ribosomeal RNA synthesis",
  "smooth endoplasmic reticulum": "found in cells specialized for hormone synthesis and detoxification",
  "rough endoplasmic reticulum": "synthesizes proteins and enzymes; covered in ribosomes",
  "endoplasmic reticulum": "system of membrane-bound tubules and cisterna",
  "ribosomes": "site of protein synthesis",
  "golgi apparatus": "stack of sacs and cisternae that sort, process and package proteins produced by the rough ER",
  "vesicles": "transport proteins out of cells",
  "lysosomes": "vesicles of enzymes that can digest microorganisms and debris",
  "acid hydrolases": "lysosome digestive enzymes",
  "peroxisomes": "smaller membrane-bound packets of enzymes",
  "oxidases": "enzymes in peroxisomes that interact with organic substances to form hydrogen peroxide",
  "mitochondria": "sites of oxidative phosphorylation and ATP formation",

}

export const microscopeTerms = {
  "microscopy": "field of using microscopes to view objects",
  "frame": "holds a microscope together",
  "stage": "holds the microscope slide",
  "fine coarse": "focus knobs that move the microscope stage up and down",
  "control": "knobs that move stage back and forth under objective",
  "objective lense": "lense closest to the stage",
  "ocular lense": "lense in microscope eyepiece",
  "chemical fixation": "kills cells and stops chemical reactions in preparation for microscope examination",
  "autolysis": "destruction of cell through the action of its own enzymes",
  "microtome": "cutting tool used to create extremely thin slices of material",
  "tangential section" : "a tissue sample that is difficult to examine under the microscope because it has been cut on an angle",
  "grazing section": "only a small portion removed from a rounded object",
  "bright stain": "principal stain",
  "counter stain": "contrasting color to the principal stain",
  "Hematoxylin": "a basic dye that binds to acidic cell components & stains them purple or blue",
  "Eosin": "an acidic stain that's going to bind to basic cell components & stains them orangy pink",
  "Eosin function": "stains cytoplasm filaments, plasma membrane, collagen fibers outside cell",
  "Hematoxylin function": "stains DNA, RNA, other carbohydrates & certain features of exocellular matrix",

}

export const tissueTermsX = {
  "adipocyte": "cell specialized in storing energy as fat",
  "fibrocyte": "type of connective tissue; a cell that produces fibers",
  "liver": "what organ's cells can have two nuclei",
  "neuroglia": "another name for glial cells",
  "muscle": "tissue that has multiple nuclei because it fused during development",
  "connective epithelial muscle nervous": "4 types of tissue (alphabetical)",
  "epithelial tissue": "usually avascular selective barrier that covers all external/internal surfaces & makes up glands",
  "pleura": "slippery epithelial membrane that secretes a small amount of fluid that acts as a lubricant, allowing the lungs to move smoothly",
  "peritoneum": "epithelial membrane in abdominopelvic cavity that pads and insulates organs, holds them in place & secretes lubricating fluid to reduce friction when rubbing",
  "connective tissue": "building materials & structural support - fat, ligaments, tendons, organ capsules, bones, cartilage",
  "muscle tissue": "excitable tissue that contracts & produces motion",
  "cardiac skeletal smooth": "3 types of muscle tissue (alphabetical)",
  "nervous tissue": "excitable tissue that is responsible for communication",
  "tendon": "connects muscle to bone",
  "ligament": "connects bone to bone at joint",
  "endothelium": "lines insides of blood vessels",
  "epidermis": "outer layer of the skin",
  "parenchymal cells": "responsible for performing the primary function of the tissue",
  "contractile apparatus": "various activities of these filaments cause muscle to shorten",
  "lumen": "inside space of a tubular structure,",
  "skin": "largest body organ",
  "skin layers": "outer epidermis, avascular epithelial layer, inner dermis, vascular connective tissue",
  "collagen fibers": "what draws ths skin into relaxed skin tension lines (wrinkles)",
  "relaxed skin tension lines": "lines parallel to the natural orientation of collagen fibers in the dermis",
  "Langer lines": "short term for RSTLs",
  "respiratory system": "transfers oxygen from alveoli to capillaries",
  "digestive system": "long glandular and muscular tube extending from oral cavity to anus",
  "urogenital system": "includes urinary system and the male & female reproductive systems",
  "ureters": "transport urine to the bladder",
  "urethra": "conveys urine from the bladder",
  "circulatory system": "distributes body fluids",
  "arteries": "send blood away from the heart",
  "veins": "send blood back to heart",
  "lymph vascular system": "drains extra fluid (called lymph) that has passed out of blood and into tissues & returns it to the blood",
  "lymph nodes": "filter substances in lymphatic fluid, contain lymphocytes (white blood cells) that help fight infection",
  "nervous system": "enables rapid and precise communication between CNS and body",
  "endocrine system": "synthesizes and secretes hormones",
  "musculoskeletal system": "bones & muscles",
  "joints": "allow bones to move",
  "ligaments": "reinforce joints",

}