//https://learning.edx.org/course/course-v1:HarvardX+AT1x+2T2024/block-v1:HarvardX+AT1x+2T2024+type@sequential+block@2778af6879ee4c6c9c7710578bc52fc8/block-v1:HarvardX+AT1x+2T2024+type@vertical+block@924ac947048e4c33a1d48ff5adddd9d8?_gl=1%2Axfvhr7%2A_gcl_au%2AMTY2MTkzNDc4OC4xNzIwMzE5NjY4%2A_ga%2AMTEwOTQyNDIzNy4xNzIwMzE5NjY4%2A_ga_D3KS4KMDT0%2AMTcyMDU2ODg3NS4yLjEuMTcyMDU2ODk0OC40OC4wLjA.

export const basicAnatomicalTerms = {
  "standard anatomical position": "face forward, palms of the hands forward, feet flat on the floor",
  "supine": "lying face upwards",
  "prone": "lying face downward",
  "aspect": "view: how you're looking at the patient",
  "anterior aspect": "view from the front",
  "posterior aspect": "view from the back",
  "lateral aspect": "view from the side",
  "superficial": "closer to the body surface",
  "deep": "farther away from the body surface",
  "superior": "closer to the head",
  "inferior": "closer to the feet",
  "medial": "closer to midline",
  "lateral": "farther from the midline",
  "proximal": "closer to the heart",
  "distal": "farther away from the heart",
  "head": "head",
  "neck": "neck",
  "thorax": "chest",
  "abdomen": "between the thorax and the pelvis",
  "pelvis": "lower part of the abdomen",
  "upper limb": "commonly known as arm",
  "brachium": "upper arm fancy",
  "arm": "upper arm simple",
  "antebrachium": "forearm",
  "hand": "hand",
  "lower limb": "hip to feet",
  "crus": "knee to ankle fancy",
  "leg": "knee to ankle simple",
  "foot": "foot",
  "thigh": "thigh",
  "sagittal plane": "divides body into left and right",
  "coronal plane": "divides body into anterior and posterior sections",
  "orthogonal": "at a right angle",
  "axial plane": "divides body into transverse sections",
  "central regions of the body": "head, neck, thorax, abdomen & pelvis"
}

export const tissuesAndOrganization = {
  "hierarchy of organization": "cells, tissues, organs, organ systems, organisms",
  "cell": "smallest independent unit of living tissue",
  "plasma membrane": "provides selective barrier between extracellular and intracellular environment",
  "cytoplasm": "cytoskeleton and cytosol",
  "cytoskeleton": "network of tubules and filaments inside cell",
  "cytosol": "cell gel",
  "microscopy": "field of using microscopes to view objects",
  "boundary membrane": "surrounds organelles",
  "organelles": "functional components of cells",
  "nucleus": "largest of cell organelles",
  "nuclear envelope": "nuclear membrane",
  "deoxyribonucleic acid": "DNA",
  "nucleolus": "site of ribosomeal RNA synthesis",
  "smooth endoplasmic reticulum": "found in cells specialized for hormone synthesis and detoxification",
  "rough endoplasmic reticulum": "synthesizes proteins and enzymes; covered in ribosomes",
  "endoplasmic reticulum": "system of membrane-bound tubules and cisterna",
  "ribosomes": "site of protein synthesis",
  "golgi apparatus": "stack of sacs and cisternae that sort, process and package proteins produced by the rough ER",
  "vesicles": "transport proteins out of cells",
  "lysosomes": "vesicles of enzymes that can digest microorganisms and debris",
  "acid hydrolases": "lysosome digestive enzymes",
  "peroxisomes": "smaller membrane-bound packets of enzymes",
  "oxidases": "enzymes in peroxisomes that interact with organic substances to form hydrogen peroxide",
  "mitochondria": "sites of oxidative phosphorylation and ATP formation"
}