export const blood1 = {
  "8" : "blood is ___% of total body weight",
  "5L" : "average volume of blood in women",
  "5.5L" : "average volume of blood in men",
  "42" : "hematocrit percent in women",
  "45" : "hematocrit percent in men",
  "90" : "plasma is ___ % water",
  "7" : "plasma is ____% proteins",
  "99" : "plasma is ___% red blood cells",
  "1" : "percentage of white blood cells & platelets in hematocrit",
  "hematocrit" : "packed cell volume",
  "erythrocytes leukocytes thrombocytes" : "3 elements in hematocrit",
  "plasma" : "liquid/fluid portion of blood",
  "water" : "primary molecule in plasma",
  "formed elements" : "fancy term for the cells in blood",
  "clotting" : "primary function of platelets",
  "erythrocytes" : "red blood cells",
  "O2 transport" : "primary function of erythrocytes",
  "leukocytes" : "immune system's mobile defence units",
  "leuko" : "means white",
  "cyte" : "means cell",
  "organs" : "are there more white blood cells in blood or orgens",
  "thrombocytes" : "platelets",
  "platelets" : "cell fragments (easier term)",
  "thrombo" : "means clot",
  "megakaryocyte" : "cell in bone marrow responsible for platelet production",
  "platelets leukocytes" : "make up buffy coat",
  "plasma buffy coat erythrocytes" : "three layers that form when blood is separated",
  "carrying regulation protection" : "three roles of blood",
  "temperature pH" : "two things that blood regulates",
  "clotting immunoglobulins" : "two ways that blood provides protection",
  "electrolytes" : "component of plasma that deals with membrane excitability",
  "sodium chrolide" : "most abundant electrolytes in plasma",
  "nutrients wastes gases hormones" : "elements in blood transported by plasma",
  "osmotic effect" : "what do plasma proteins exert",
  "collid" : "how plasma proteins are dispersed in plasma",
  "no" : "do plasma proteins diffuse through capillary wall? Yes or no",
  "pH buffer" : "secondary responsibility of plasma proteins",
  "liver" : "where are most plasma proteins synthesized",
  "gamma globulins" : "the only plasma protein not synthesized in liver",
  "lymphocytes" : "what produces gamma globulins",
  "into" : "do plasma proteins prevent water from rushing into or out of cells",
  "hydrostatic" : "is hydrostatic or osmotic pressure higher in blood",
  "albumins globulins fibrinogen" : "3 types of plasma proteins",
  "albumins" : "the plasma proteins mainly responsible for transporing substances",
  "albumin" : "the most abundant protein in plasma that contributes the most to osmotic pressure",
  "non" : "are albumins specific or non",
  "water-soluble" : "what types of molecules do albumins help transport",
  "1/2" : "how much of plasma protein is albumin (fraction)",
  "alpha beta gamma" : "three types of globulins",
  "specific" : "are alpha and beta globulins specific or non",
  "carriers" : "primary function of alpha and beta globulins",
  "water-insoluble" : "what types of molecules do alpha and beta globulins help transport",
  "cholesterol iron complement" : "three specific molecules alpha and beta globulins help transport",
  "gamma" : "antibody globulins",
  "defenders" : "primary role of gamma globulins",
  "fibrinogen" : "inactive precursor for a clot's fibrin meshwork",
  "5 billion" : "how many red blood cells per mL of blood",
  "shape content" : "what adaptations do red blood cells have to help fulfil primary function",
  "biconcave disc" : "shape of red blood cell",
  "surface area thinness" : "what two features are particularly noteworthy about RBC's membrane due to its shape",
  "flexible" : "unique trait of the RBC's plasma membrane",
  "fragile" : "are RBCs strong or fragile",
  "nucleus organelles ribosomes" : "3 things RBCs are missing",
  "8uM 3uM" : "RBC diameter range",
  "not water soluble" : "why does O2 need a carrier in the blood",
  "hemoglobin" : "protein in red blood cells that binds with oxygen",
  "4" : "how many oxygen molecules can hemoglobin carry",
  "iron" : "what does hemoglobin pigment contain",
  "Fe" : "what element binds with oxygen in hemoglobin",
  "reddish" : "what colour does the heme group appear when oxygenated",
  "bluish" : "what colour does the heme group appear when deoxygenated",
  "polypeptide" : "each iron-containing non-protein group is bound do one ____",
  "reversibly" : "how does iron bind to oxygen molecules",
  "heme group" : "what molecule does oxygen bind with in hemoglobin",
  "globin" : "protein in blood composed of 4 highly folded peptide chains",
  "alpha beta 2" : "what are the subunits of globin, and how many of each?",
  "carry O2" : "primary role of hemoglobin",
  "98.5" : "what percentage of O2 in blood is bound to Hb",
  "250 million" : "how many Hb molecules in one RBC",
  "1 billion" : "how many O2 molecules can be carried by 1 RBC",
  "carbon dioxide" : "a secondary molecule hemoglobin can combine with",
  "acidic hydrogen ion" : "an ion hemoglobin can combine with to buffer pH",
  "ionized carbonic acid" : "what substance creates the H+ hemoglobin can combine with",
  "carbon monoxide" : "lethal substance hemoglobin can combine with",
  "nitric oxide" : "substance hemoglobin can bind with that stabilises blood pressure",
  "vasodilator" : "word that defines nitric oxide by describing its role in the body",
  "dialates" : "nitric oxide ___ arterioles in lungs",
  "glycolytic enzymes" : "enzyme in RBCs vitale for generating energy needed to survive",
  "glycolisis" : "what do RBCs use to create energy",
  "anaerobic" : "what type of respiration do RBCs rely on",
  "carbonic ahydrase" : "enzyme critical in CO2 transport",
  "bicarbonate ion" : "what is the form of CO2 that is transported in blood",
  "HC03-" : "chemical formula for bicarbonate ion",
}