export const blood1 = {
  "8" : "blood is ___% of total body weight",
  "5L" : "average volume of blood in women",
  "5.5L" : "average volume of blood in men",
  "42" : "hematocrit percent in women",
  "45" : "hematocrit percent in men",
  "90" : "plasma is ___ % water",
  "7" : "plasma is ____% proteins",
  "99" : "hematocrit is ___% red blood cells",
  "1" : "percentage of white blood cells & platelets in hematocrit",
  "hematocrit" : "packed cell volume",
  "erythrocytes leukocytes thrombocytes" : "3 elements in hematocrit",
  "plasma" : "liquid/fluid portion of blood",
  "water" : "primary molecule in plasma",
  "formed elements" : "fancy term for the cells in blood",
  "clotting" : "primary function of platelets",
  "erythrocytes" : "red blood cells",
  "leukocytes" : "immune system's mobile defence units",
  "leuko" : "means white",
  "cyte" : "means cell",
  "organs" : "are there more white blood cells in blood or organs",
  "thrombocytes" : "platelets",
  "platelets" : "cell fragments (easier term)",
  "thrombo" : "means clot",
  "megakaryocyte" : "cell in bone marrow responsible for platelet production",
  "platelets leukocytes" : "make up buffy coat",
  "plasma buffy coat erythrocytes" : "three layers that form when blood is separated",
  "carrying regulation protection" : "three roles of blood",
  "temperature pH" : "two things that blood regulates",
  "clotting immunoglobulins" : "two ways that blood provides protection",
  "electrolytes" : "component of plasma that deals with membrane excitability",
  "sodium chloride" : "most abundant electrolytes in plasma",
  "nutrients wastes gases hormones" : "elements in blood transported by plasma",
  "osmotic effect" : "what do plasma proteins exert",
  "collid" : "how plasma proteins are dispersed in plasma",
  "no" : "do plasma proteins diffuse through capillary wall? Yes or no",
  "pH buffer" : "secondary responsibility of plasma proteins",
  "liver" : "where are most plasma proteins synthesized",
  "gamma globulins" : "the only plasma protein not synthesized in liver",
  "lymphocytes" : "what produces gamma globulins",
  "into" : "do plasma proteins prevent water from rushing into or out of cells",
  "hydrostatic" : "is hydrostatic or osmotic pressure higher in blood",
  "albumins globulins fibrinogen" : "3 types of plasma proteins",
  "albumins" : "the plasma proteins mainly responsible for transporing substances",
  "albumin" : "the most abundant protein in plasma that contributes the most to osmotic pressure",
  "non" : "are albumins specific or non",
  "water-soluble" : "what types of molecules do albumins help transport",
  "1/2" : "how much of plasma protein is albumin (fraction)",
  "alpha beta gamma" : "three types of globulins",
  "specific" : "are alpha and beta globulins specific or non",
  "carriers" : "primary function of alpha and beta globulins",
  "water-insoluble" : "what types of molecules do alpha and beta globulins help transport",
  "cholesterol iron complement" : "three specific molecules alpha and beta globulins help transport",
  "gamma" : "antibody globulins",
  "defenders" : "primary role of gamma globulins",
  "fibrinogen" : "inactive precursor for a clot's fibrin meshwork",
  "5 billion" : "how many red blood cells per mL of blood",
  "shape content" : "what adaptations do red blood cells have to help fulfil primary function",
  "biconcave disc" : "shape of red blood cell",
  "surface area thinness" : "what two features are particularly noteworthy about RBC's membrane due to its shape",
  "flexible" : "unique trait of the RBC's plasma membrane",
  "fragile" : "are RBCs strong or fragile",
  "nucleus organelles ribosomes" : "3 things RBCs are missing",
  "8uM 3uM" : "RBC diameter range",
  "not water soluble" : "why does O2 need a carrier in the blood",
  "hemoglobin" : "protein in red blood cells that binds with oxygen",
  "4" : "how many oxygen molecules can hemoglobin carry",
  "iron" : "what does hemoglobin pigment contain",
  "Fe" : "what element binds with oxygen in hemoglobin",
  "reddish" : "what colour does the heme group appear when oxygenated",
  "bluish" : "what colour does the heme group appear when deoxygenated",
  "polypeptide" : "each iron-containing non-protein group is bound to one ____",
  "reversibly" : "does iron bind to oxygen molecules reversibly or irreversibly",
  "heme group" : "what part does oxygen bind with in hemoglobin",
  "globin" : "protein in blood composed of 4 highly folded peptide chains",
  "alpha beta 2" : "what are the subunits of globin, and how many of each?",
  "carry O2" : "primary role of hemoglobin",
  "98.5" : "what percentage of O2 in blood is bound to Hb",
  "250 million" : "how many Hb molecules in one RBC",
  "1 billion" : "how many O2 molecules can be carried by 1 RBC",
  "carbon dioxide" : "a secondary molecule hemoglobin can combine with",
  "acidic hydrogen ion" : "an ion hemoglobin can combine with to buffer pH",
  "ionized carbonic acid" : "what substance creates the H+ hemoglobin can combine with",
  "carbon monoxide" : "lethal substance hemoglobin can combine with",
  "nitric oxide" : "substance hemoglobin can bind with that stabilises blood pressure",
  "vasodilator" : "word that defines nitric oxide by describing its role in the body",
  "glycolytic enzymes" : "enzymes in RBCs, vital for generating energy needed to survive",
  "anaerobic glycolysis" : "how do RBCs create energy",
  "carbonic ahydrase" : "enzyme critical in CO2 transport",
  "bicarbonate ion" : "what is the form of CO2 that is transported in blood",
  "HC03negative" : "chemical formula for bicarbonate ion (partially written)",
}

export const redBloodCells = {
  "120" : "how many days do RBCs live",
  "30 trillion" : "max number of RBCs that travel in our vessels at once",
  "3" : "what is the cells-per-second turn-over of red blood cells",
  "spleen" : "organ that removes most old erythrocytes & recycles components",
  "erythroblast" : "the last phase of RBC development that still has a nucleus & organelles",
  "pluripotent" : "a stem cell that's able to create other types of cells",
  "differentiate" : "term referring to how a developing cell can become a different type of cell",
  "stem cell" : "simple term for specialized cell in bone marrow",
  "myeloiod stem cell" : "the second phase of erythrocyte development",
  "reticulocyte" : "precurser to mature RBC - organelles disappearing",
  "erythrocyte" : "cell that travels out from bone marrow into blood stream",
  "1" : "how many phases of the 5 phases of RBC development can be seen outside bone marrow",
  "erythropoiesis" : "generation of new red blood cells",
  "poiesis" : "means making / generation / formation",
  "red bone marrow" : "where does erythropoiesis happen",
  "kidneys" : "what organs detect reduced O2 carrying capacity of blood",
  "O2" : "what is the signal for needing to increase RBC count",
  "erythropoietin" : "hormone that signals there is low O2 in blood",
  "kidney" : "what organ releases erythropoietin (singular)",
  "altitude" : "one external factor that can trigger erythropoiesis",
  "antigen" : "large, complex molecule that trigggers a specific immune response against itself when it gains entry into body",
  "lymphocytes" : "what detect antigens and create antibodies against them - most powerful immune cells",
  "antibodies" : "what binds with specific antigen against which it is produced & leads to antigen's destruction",
  "plasma" : "where AB antibodies are found in blood",
  "erythrocytes" : "where AB antigens are found in blood",
  "A" : "blood type that produces Anti-B antibodies",
  "B" : "blood type that produces Anti-A antibodies",
  "AB" : "blood type that produces no AB antibodies in plasma",
  "O" : "blood type that produces both Anti-A and Anti-B antibodies",
  "A antigens" : "primary factor that determines Type A blood",
  "B antigens" : "primary factor that determines Type B blood",
  "A and B" : "what antigens does AB blood have",
  "none" : "what antigens does type O blood have",
  "6 months" : "how old does a person have to be to have an AB blood type",
  "agglutinate rupture" : "what happens to blood after transfusion if it's not the correct blood type",
  "hemoglobin precipitates kidneys" : "___  ___ in _____ following agglutination and rupturing of RBCs",
  "O positive" :  "most common blood type",
  "A positive" : "second most common blood type",
  "negative" : "most uncommon blood types all have this feature",
  "B-cells" : "what type of lymphocytes make antibodies",
  "Karl Landsteiner" : "Nobel Prize winner for ABO blood type discovery",
  "gamma globulins" : "what molecules have antibodies that can be Anti-B or Anti-A",
  "food" : "where do scientists think we got these antibodies from",
  "natural" : "are AB antibodies natural(ly-occurring) or developed",
  "carbohydrate" : "what type of molecule on food triggered the production of A/B antibodies",
  "Rhesus" : "Rh meaning",
  "50" : "how many blood-group antigens are there",
  "Fischer Race System" : "what is another name for the D, C, E, c, e blood categorization",
  "alleles" : "alternative forms of the same antigen",
  "d" : "what doesn't belong? D, C, E, d, c, e",
  "no" : "if someone has C antigen, will it have matching c antigen?",
  "Rh factor" : "older term for Rh+",
  "D" : "what antigen does Rh+ and Rh- refer to",
  "have" : "people who ____ Rh factor have Rh+ blood (D)",
  "exposure to Rh positive" : "what makes Anti-Rh antibodies develop",
  "Rh negative" : "what types of people can produce Anti-Rh antibodies",
  "Rh positive" : "what are you if you have the D antigen",
  "can" : "Rh negative people ____ produce antibodies",
  "yes" : "can Rh- people recieve Rh+ blood in an emergency?",
  "delayed" : "is reaction to wrong Rh factor always 'immediate' or can it be 'delayed'",
  "donate" : "can Type O 'donate' to everyone or 'receive' from everyone",
  "receive" : "can Type AB 'donate' to everyone or 'receive' from everyone",
  "both" : "can Rh+ person receive from positive, negative or both"
}