import {  TermObject } from "./deckObject";


export const cellTerms: TermObject = {
  "cell theory" : "cell is the basic unit of life",
  "Theodor Schwann" : "developed cell theory",
  "plasma membrane" : "thin membranous structure that encloses each cell",
  "phospholipid bilayer" : "name for plasma membrane that explains what its made out of",
  "mosaic" : "one word that describes the makeup of the plasma membrane",
  "nucleus" : "houses the cell's genetic material",
  "double" : "does nucleus have a single or double membrane",
  "deoxyribonucleic acid" : "DNA",
  "organelles" : "subcellular structures that has one or more specific jobs to perform in the cell",
  "endoplasmic reticulum" : "produces proteins & lipids",
  "rough endoplasmic reticulum" : "synthesizes proteins",
  "smooth endoplasmic reticulum" : "synthesizes lipids",
  "golgi complex" : "modifies, packages & distributes newly synthesized proteins",
  "lysosomes" : "break down organic molecules with enzymes",
  "hydrolytic" : "the type of enzymes in lysosomes",
  "peroxisomes" : "detoxify waste products",
  "oxidative" : "the type of enzymes in peroxisomes",
  "centrioles" : "form & organize microtubules during cell division",
  "mitotic spindle" : "tubular structure made during cell division",
  "trachea" : "an example of where cilia are",
  "sperm" : "the only human cell with flagella",
  "microtubules" : "long, hollow tubes",
  "mitochondria" : "energy organelles",
  "matrix" : "gel-like fluid inside mitochondria",
  "cristae" : "name for folds in mitochondria's inner membrane",
  "intermembrane space" : "space between mitochondria's two membranes",
  "Adenosine TriPhosphate" : "ATP",
  "citric acid cycle" : "TCA",
  "cytosol" : "cell gell",
  "cytoskeleton" : "holds cell shape & allows it to move",
  "tubulin" : "protein that microtubules are made of",
  "molecular highways" : "fun name for microtubules that explains one of their functions",
  "microfilaments" : "smallest of cytoskeleton proteins",
  "no" : "are microfilaments hollow?",
  "actin" : "main protein that microfilaments are made of",
  "myosin" : "a microfilament-involved protein present in muscle cells",
  "mechanical stiffener" : "the role of microfilaments in the microvilli in intestine",
  "intermediate filaments" : "irregular, threadlike proteins that help resist mechanical stress",
  "keratin" : "an intermediate filament example; found in hair, nails",
  "intermediary metabolism" : "process that occurs in the cytosol & involves thousands of enzymes",
  "enzymes" : "there are thousands of these in the cytosol",
  "vesicles" : "transient structures in cytosol used for moving things through the cell",
  "inclusions" : "stores of excess nutrients, such as glycogen & fatty acids",
  "adipose" : "the type of tissue that stores fat",
}

export const cellularRespiration: TermObject = {
  "anabolism" : "the building-up aspect of metabolism",
  "catabolism" : "the breakdown down aspect of metabolism that releases energy",
  "anabolic steroids" : "substance that builds up complex proteins",
  "degradation" : "the process by which substances are destroyed in the cell",
  "synthesis" : "the process that joins smaller molecules",
  "glucose" : "the best molecule to build ATP from",
  "carbon bonds" : "what releases the energy when obtaining energy through ATP",
  "substrate-level phosphorylation" : "ATP -> ADP",
  "phosphate group" : "what is released when ATP releases energy",
  "creatine kinase" : "enzyme that facilitates CP cycle",
  "creatine phosphate system" : "CP process long name",
  "5" : "how much more CP in skeletal muscle than ATP at rest",
  "fast" : "is CP system fast or slow",
  "32" : "how many ATP created per molecule of glucose in cellular respiration",
  "glycolysis" : "the first stage of cellular respiration",
  "10" : "number of reactions in glycolysis",
  "pyruvate" : "3-carbon molecule that is a product of glycolysis",
  "McArdle" : "disease stemming from absence of enzyme involved in first step of glycolysys",
  "pyruvate decarboxylation" : "first reaction that happens when product of glycolysis enters the mitochondrial matrix",
  "matrix" : "area in mitochondria where citric acid cycle happens",
  "Acetyl-CoA" : "product of pyruvate decarboxylation",
  "tricarboxylic acid cycle" : "longest name for the citric acid cycle",
  "citric acid cycle" : "fruit-sounding name for the Krebs cycle",
  "Krebs" : "the guy's name version of the citric acid cycle",
  "8" : "number of steps in the citric acid cycle",
  "citrate" : "6C molecule that's a stage in the citric acid cycle",
  "oxaloactate" : "4C molecule in Krebs cycle that's ready to receive a new Acetyl-CoA",
  "CO2" : "product of citric acid cycle & pyruvate decarboxylation that is sent as waste out to bloodstream",
  "cycle" : "is the O2 used to form CO2 in citric acid cycle from breathing or the cycle?",
  "hydrogen" : "the key point of the citric acid cycle is to remove this item over 4 steps (word)",
  "nicotinamide adenine dinucleotide" : "the positively charged substance that catches hydrogen in the Krebs cycle",
  "flavine adenine dinucleotide" : "the non-charged substance that catches hydrogen molecules in the tricarboxylic acid cycle",
  "NAD+" : "nicotinamide adenine dinucleotide",
  "FAD" : "flavine adenine dinucleotide",
  "guanosine diphosphate" : "some of energy released in citric acid cycle goes toward linking inorganic phosphate to this",
  "NADH FADH2" : "crucial products of citric acid cycle",
  "oxidative phosphorylation" : "the umbrella term for the ETC and chemiosmosis",
  "electron transport chain" : "ETC",
  "NAD+ FAD" : "the link between TCA and ETC (the product of ETC version)",
  "2.5" : "How many ATPs per 1 NADH",
  "1.5" : "How many ATPs per 1 FADH2",
  "lower" : "high-energy electrons move to _____ energy levels as they are transferred from carrier to carrier through ETC",
  "H+" : "in ETC, some of released energy is used to transport what substance from matrix into the intermembrane space",
  "Complex I, III, IV" : "where does H+ travel through to intermembrane space in ETC",
  "intermembrane space" : "in ETC, are H+ ions more concentrated in intermembrane space or matrix",
  "ATP synthase" : "enzyme that drives ATP production",
  "H+ gradient" : "what supplies energy that drives ATP synthesis",
  "lactate" : "if there is no extra oxygen, what is pyruvate converted into",
  "anaerobic" : "what condition makes pyruvate be converted to lactate instead of ACoA",
  "more" : "do aerobic pathways create more or less energy?",
  "chemiosmosis" : "the movement of hydrogen ions across the membrane via ATP synthase",
  "2" : "number of NADH produced in glycolysis",
  "two" : "number of NADH produced in pyruvate decarboxylation (written)",
  "6 2" : "number of NADH and FADH2 produced in TCA cycle",
  "1" : "number of CO2 produced per pyruvate in pyruvate decarboxylation",
  "ten" : "number of NADH per glucose molecule that heads into ETC (written)",
  "2 2 3" : "how many NADH heading into ETC: ___ from glycolysis, ____ from pyruvate, ____ per TCA cycle",
  "6" : "number of CO2 waste per glucose molecule heading into ETC",
  "Complex I" : "where NADH gives off its electron",
  "Complex II" : "where FADH2 gives off its ion",
  "Complex III" : "accepts FADH2's ion because other channel doesn't go all the way through",
  "3" : "how many hydrogen ions pumped from NADH into intermembrane space",
  "fatty acids proteins" : "what are two other substances that can enter cycle at Acetyl-CoA step if starved",
}

export const membraneTerms: TermObject = {
  "plasma membrane" : "another name for cell membrane",
  "extracellular" : "space outside of cell",
  "intracellular" : "space within a cell",
  "phospholipid" : "most abundant membrane lipid",
  "cholesterol" : "a second type of membrane lipid (not the obvious)",
  "polar" : "a molecule that has a positive and negative end",
  "nonpolar" : "a molecule that doesn't have a charge on either end",
  "hydrophilic" : "trait of the phospholipid head",
  "hydrophobic" : "trait of the phospholipid tail",
  "lipid protein carbohydrate" : "3 most common molecule types in the cell membrane",
  "Fluid Mosaic Model" : "refers to the changing pattern of proteins on lipid bilayer",
  "iceberg" : "a protein in the membrane is like an ______ on water",
  "50x" : "how many more lipid molecules than protein molecules",
  "50%" : "how much of membrane's mass is made up of protein",
  "channel" : "membrane protein that allows for passage of small water-soluble molecules",
  "CAMs ECMs specialized cell junctions" : "three ways cells are stuck together",
  "carrier molecule" : "membrane protein that transfers specific substances",
  "docking-marker acceptor" : "membrane protein involved with secretory vesicles & exocytosis",
  "membrane-bound enzyme" : "membrane protein that helps facilitate chemical reactions",
  "receptor" : "membrane protein that recognizes & decodes extracellular signals",
  "cell adhesion molecule" : "membrane protein that establishes direct adhesion between cells",
  "not" : "CAMs are ____ strong",
  "communication" : "important role of CAMs (besides binding)",
  "velcro" : "man-made substance similar to role of CAMs in structure and use",
  "peripheral" : "membrane protein that adheres only temporarily to the biological membrane with which they are associated",
  "extracellular matrix" : "ECM",
  "interstitial fluid" : "gel-like pathway in ECM for diffusion of nutrients, wastes, and other water- soluble traffic between the blood and tissue cells",
  "ECM" : "meshwork of fibrous proteins embedded in watery, gel-like substance",
  "complex carbohydrates" : "what interstitial fluid is made out of",
  "collagen" : "abundant protein fiber woven through gel; forms cable-like fibers",
  "1/2" : "collagen is ___ total body protein by weight (fraction)",
  "tensile strength" : "helps protein not be pulled apart when stretched",
  "elastin" : "rubber-like protein fiber that stretches and recoils",
  "lungs" : "place where elastin protein is abundant (incl. 's')",
  "fibronectin" : "promotes cell adhesion & holds cells in position",
  "tumour metastasis" : "lowered fibronectin levels are a sign of this",
  "biological glue" : "purpose of protein fibers in extracellular matrix",
  "epithelial tissue" : "where are protein fibers scant",
  "connective tissue" : "where are protein fibers abundant",
  "fibroblasts" : "where are protein fibers made / secreted",
  "desmosomes" : "adhering junctions that anchor together two adjacent but non-touching cells",
  "tight junctions" : "impermeable junctions that seal off the passageway between the two cells",
  "gap junctions" : "communicating junctions",
  "desmosomes tight gap" : "3 types of specialised cell junctions",
  "spot rivets" : "what desmosomes act like",
  "extreme mechanical pressure" : "desmosomes help cells stay togehter through ____",
  "stretching" : "key function desmosomes assist with; are most abundant in tissues that do this",
  "cadherins" : "what very strong proteins make up intercellular filaments in desmosomes",
  "cytoplasmic thickening plaques" : "what creates plate to strengthen adhesion in desmosomes",
  "intracellular keratin filaments" : "what connects the desmosome to the inside of the cell, creating strength",
  "epithelial" : "type of tissue that has lots of tight junctions",
  "gut" : "common place for tight junctions",
  "no" : "can water go through tight junctions",
  "lumen" : "inside space of a tubular structure",
  "connexons" : "small, connecting tunnels between adjacent cells in gap junctions",
  "communicating junctions" : "joins that allow small, water-soluble particles to pass between the connected cells but doesn't allow passage of large molecules",
  "cardiac smooth" : "2 types of muscle where gap junctions are common",
  "gap" : "type of junction that allows movement of ions to transmit electrical activity - help synchronized contractions of a whole muscle mass",
}

export const passiveMembraneTransport = {
  "small" : "are connexons big or small",
  "no" : "can water soluble molecules cross membrane without assistance?",
  "solubility size" : "two properties that influence whether a substance can permeate the plasma membrane without any assistance",
  "uncharged nonpolar" : "2 types of molecules that easily permeate the plasma membrane",
  "lipid" : "molecules that pass through membrane easily need to be soluble in this",
  "charged polar" : "2 types of molecules with low lipid solubility and are very soluble in water",
  "channels" : "what ions use to travel through membrane",
  "degree" : "is solubility a yes or no or degree",
  "assisted" : "type of transport used by proteins & glucose",
  "large" : "why can't proteins & glucose travel through channels",
  "active" : "forces that require the cell to expend energy",
  "passive" : "forces that do not require the cell to spend energy",
  "negative" : "is phospholipid head negative or positive",
  "hydrocarbons" : "the water-hating molecules that are phospholipid's tails",
  "covalent" : "what kind of bonds are in water",
  "oxygen" : "molecule that can easily go through membrane",
  "down" : "what direction does diffusion go according to the gradient",
  "concentration gradient" : "difference in concentration on sides of membrane",
  "electrical gradient" : "difference in membrane potential",
  "random" : "what direction of motion do molecules travel in",
  "diffusion" : "movement of particle from high concentraton to low concentration",
  "steady state" : "equilibrium",
  "equilibrium" : "steady state",
  "chemical" : "is concentration gradient chemical or electrical",
  "gradient" : "what provides the force in diffusion",
  "net diffusion" : "when there are an equal number of like particles moving in each direction",
  "Ficks" : "Whose law of diffusion?",
  "magnitude, surface area, lipid solubility" : "3 factors that increase the rate of net diffusion",
  "molecular weight, distance" : "3 factors that decrease the rate of net diffusion",
  "magnitude" : "Fick's Law: the steepness of the concentration gradient",
  "surface area" : "Fick's Law: the largeness of the cell's membrane",
  "lipid solubility" : "Fick's Law: the substance's ability to not be repelled by the membrane",
  "molecular weight" : "Fick's Law: how big the substance is that is trying to cross",
  "distance" : "Fick's Law: how thick the membrane wall is",
  "projections" : "what might cells have to increase their permeability (via surface area)",
  "red blood cells" : "type of cell with an extremely thin plasma membrane",
  "ion" : "electrically charged particle",
  "concentration charge" : "two things that can affect movement across membrane",
  "cation" : "positively charged ion",
  "calcium" : "example of positively charged ion",
  "chloride" : "example of negatively charged ion",
  "anion" : "negatively charged ion",
  "electrochemical gradient" : "combined effect of concentration & electrical gradient",
  "positive negative" : "which charges do you need to count to calculate electrical gradient",
  "overall one type of" : "the electrical gradient depends on the ___ charge, and the chemical gradient is affected by ____ molecule(s)",
  "membrane aquaporins" : "two ways water can get in cell",
  "aquaporins" : "special water channels in cells",
  "concentration gradient force" : "what is the driving force behind water coming in/out of the cell (incl. 'force')",
  "osmosis" : "net diffusion of water",
  "concentration" : "density of a solute - the key determiner of a steady state, not number of molecules",
  "solute" : "dissolved substance",
  "decreases" : "adding solute to pure water ___ the water concentration",
  "osmotic pressure" : "'pulling' pressure that is measure of tendency for water to move into solution due to concentration of non-penetrating solutes & water",
  "hydrostatic pressure" : "fluid pressure - caused from rise in volume",
  "fluid pressure" : "hydrostatic pressure",
  "hydrostatic" : "pressure exerted by a standing, stationary fluid on an object",
  "dynamic equilibrium" : "when osmosis ceases because osmotic pressure and hydrostatic pressure make a net 0 force",
  "false" : "True or false: at equilibrium, molecules no longer cross the membrane",
  "volume" : "what changes in cell when number of molecules is different",
}