import {  TermObject } from "./deckObject";


export const cellTerms: TermObject = {
  "cell theory" : "cell is the basic unit of life",
  "Theodor Schwann" : "developed cell theory",
  "plasma membrane" : "thin membranous structure that encloses each cell",
  "phospholipid bilayer" : "name for plasma membrane that explains what its made out of",
  "mosaic" : "one word that describes the makeup of the plasma membrane",
  "nucleus" : "houses the cell's genetic material",
  "double" : "does nucleus have a single or double membrane",
  "deoxyribonucleic acid" : "DNA",
  "organelles" : "subcellular structures that has one or more specific jobs to perform in the cell",
  "endoplasmic reticulum" : "produces proteins & lipids",
  "rough endoplasmic reticulum" : "synthesizes proteins",
  "smooth endoplasmic reticulum" : "synthesizes lipids",
  "golgi complex" : "modifies, packages & distributes newly synthesized proteins",
  "lysosomes" : "break down organic molecules with enzymes",
  "hydrolytic" : "the type of enzymes in lysosomes",
  "peroxisomes" : "detoxify waste products",
  "oxidative" : "the type of enzymes in peroxisomes",
  "centrioles" : "form & organize microtubules during cell division",
  "mitotic spindle" : "tubular structure made during cell division",
  "trachea" : "an example of where cilia are",
  "sperm" : "the only human cell with flagella",
  "microtubules" : "long, hollow tubes",
  "mitochondria" : "energy organelles",
  "matrix" : "gel-like fluid inside mitochondria",
  "cristae" : "name for folds in mitochondria's inner membrane",
  "intermembrane space" : "space between mitochondria's two membranes",
  "Adenosine TriPhosphate" : "ATP",
  "citric acid cycle" : "TCA",
  "cytosol" : "cell gell",
  "cytoskeleton" : "holds cell shape & allows it to move",
  "tubulin" : "protein that microtubules are made of",
  "molecular highways" : "fun name for microtubules that explains one of their functions",
  "microfilaments" : "smallest of cytoskeleton proteins",
  "no" : "are microfilaments hollow?",
  "actin" : "main protein that microfilaments are made of",
  "myosin" : "a microfilament-involved protein present in muscle cells",
  "mechanical stiffener" : "the role of microfilaments in the microvilli in intestine",
  "intermediate filaments" : "irregular, threadlike proteins that help resist mechanical stress",
  "keratin" : "an intermediate filament example; found in hair, nails",
  "intermediary metabolism" : "process that occurs in the cytosol & involves thousands of enzymes",
  "enzymes" : "there are thousands of these in the cytosol",
  "vesicles" : "transient structures in cytosol used for moving things through the cell",
  "inclusions" : "stores of excess nutrients, such as glycogen & fatty acids",
  "adipose" : "the type of tissue that stores fat",
}

export const cellularRespiration = {
  "anabolism" : "the building-up aspect of metabolism",
  "catabolism" : "the breakdown down aspect of metabolism that releases energy",
  "anabolic steroids" : "substance that builds up complex proteins",
  "degradation" : "the process by which substances are destroyed in the cell",
  "synthesis" : "the process that joins smaller molecules",
  "glucose" : "the best molecule to build ATP from",
  "carbon bonds" : "what releases the energy when obtaining energy through ATP",
  "substrate-level phosphorylation" : "ATP -> ADP",
  "phosphate group" : "what is released when ATP releases energy",
  "creatine kinase" : "enzyme that facilitates CP cycle",
  "creatine phosphate system" : "CP process long name",
  "5" : "how much more CP in skeletal muscle than ATP at rest",
  "fast" : "is CP system fast or slow",
  "32" : "how many ATP created per molecule of glucose in cellular respiration",
  "glycolysis" : "the first stage of cellular respiration",
  "10" : "number of reactions in glycolysis",
  "pyruvate" : "3-carbon molecule that is a product of glycolysis",
  "McArdle" : "disease stemming from absence of enzyme involved in first step of glycolysys",
  "pyruvate decarboxylation" : "first reaction that happens when product of glycolysis enters the mitochondrial matrix",
  "matrix" : "area in mitochondria where citric acid cycle happens",
  "Acetyl-CoA" : "product of pyruvate decarboxylation",
  "tricarboxylic acid cycle" : "longest name for the citric acid cycle",
  "citric acid cycle" : "fruit-sounding name for the Krebs cycle",
  "Krebs" : "the guy's name version of the citric acid cycle",
  "8" : "number of steps in the citric acid cycle",
  "citrate" : "6C molecule that's a stage in the citric acid cycle",
  "oxaloactate" : "4C molecule in Krebs cycle that's ready to receive a new Acetyl-CoA",
  "CO2" : "product of citric acid cycle & pyruvate decarboxylation that is sent as waste out to bloodstream",
  "cycle" : "is the O2 used to form CO2 in citric acid cycle from breathing or the cycle?",
  "hydrogen" : "the key point of the citric acid cycle is to remove this item over 4 steps (word)",
  "nicotinamide adenine dinucleotide" : "the positively charged substance that catches hydrogen in the Krebs cycle",
  "flavine adenine dinucleotide" : "the non-charged substance that catches hydrogen molecules in the tricarboxylic acid cycle",
  "NAD+" : "nicotinamide adenine dinucleotide",
  "FAD" : "flavine adenine dinucleotide",
  "guanosine diphosphate" : "some of energy released in citric acid cycle goes toward linking inorganic phosphate to this",
  "NADH FADH2" : "crucial products of citric acid cycle",
  "oxidative phosphorylation" : "the umbrella term for the ETC and chemiosmosis",
  "electron transport chain" : "ETC",
  "NAD+ FAD" : "the link between TCA and ETC (the product version)",
  "2.5" : "How many ATPs per 1 NADH",
  "1.5" : "How many ATPs per 1 FADH2",
  "lower" : "high-energy electrons move to _____ energy levels as they are transferred from carrier to carrier through ETC",
  "H+" : "in ETC, some of released energy is used to transport what substance from matrix into the intermembrane space",
  "Complex I, III, IV" : "where does H+ travel through to intermembrane space in ETC",
  "intermembrane space" : "in ETC, are H+ ions more concentrated in intermembrane space or matrix",
  "ATP synthase" : "enzyme that drives ATP production",
  "H+ gradient" : "what supplies energy that drives ATP synthesis",
  "lactate" : "if there is no extra oxygen, what is pyruvate converted into",
  "anaerobic" : "what condition makes pyruvate be converted to lactate instead of ACoA",
  "more" : "do aerobic pathways create more or less energy?",
}