//https://www.youtube.com/watch?v=i5tR3csCWYo&list=PL8dPuuaLjXtOAKed_MxxWBNaPno5h3Zs8&index=3

export const tissueTerms = {
  "cell specialization": "process by which generic cells change into specific cells meant to do certain tasks within the body",
  "tissues": "groups of similar cells come together to perform a common function",
  "organs": "when two or more tissues combine",
  "nervous tissue": "tissue that provides us with control and communication",
  "muscle tissue": "tissue that gives us movement",
  "epithelial tissue": "tissue that lines body cavities and organs",
  "connective tissue": "tissue that provides support to body",
  "histology": "study of our tissues",
  "Hans and Zacharias Jansen": "developed first microscope in 1590's",
  "Anton van Leeuwenhoek": "made first truly high-powered microscope in late 1600's - 270x magnifying power",
  "Anton van Leeuwenhoek nickname": "The father of Microbiology",
  "stains and dyes": "allow us to see things in cells that aren't possible with just microscope",
  "nucleus": "membrane-enclosed organelle within a cell that contains chromosomes",
  "Joseph von Gerlach": "developed first true histological stain in 1850's - neural stain accident",
  "carmine": "red dye derived from scales of crushed-up cochineal insects used in early staining",
  "central nervous system": "brain & spinal cord",
  "peripheral nervous system": "network of nerves throughout body",
  "nervous tissue functions": "sensing stimuli & sending electrical impulses through body",
  "neurons": "nerve cells that send messages all over your body",
  "glial cells": "cells that hold nerve cells in place and help them work the way they should; tether them to blood vessels",
  "cell body": "easy name for neuron's life support; nucleus, mitochondria & DNA",
  "soma": "another term for neuron's cell body",
  "dendrites": "neuron's bushy & tree-like listeners - collect signals from other cells to send back to soma",
  "axon": "neuron's transmission cable that carries messages to other neurons, muscles & glands",
  "skeletal muscle": "long, multinucleate parallel voluntary muscle cells with striations attached to skeleton",
  "striations": "fine black lines running perpendicular to skeletal muscle fibers",
  "cardiac muscle": "involuntary muscle cells that divide & converge; one nucleus per cell, striated with intercalated disks",
  "intercalated disks": "glue that holds muscle cells together when contracting; contain pores for signal pass-through",
  "uninucleate": "one nucleus per cell",
  "smooth muscle": "short, tapered involuntary muscle cells, but no striations; lines walls of blood vessels & some organs",
}